seed: 0
dataset: AD-1
step_width: 1000
learning_rate: 1e-4
warmup_steps: 1000
weight_decay: 0.0
batch_size: 32
num_epochs: 1000
patience: 100
data_augmentation: true
measure_equivariance_discrepancy: false
use_aml_logging: false
model_config:
  model_type: gaussian_density_transformer
  gaussian_density_transformer_config:
    atom_embedding_dim: 16
    latent_dim: 128
    latent_mlp_hidden_dims: [256]
    num_transformer_layers: 6
    transformer_config:
      n_head: 8
      dim_feedforward: 2048
      dropout: 0
